<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

/**
 * @property  mixed name
 * @property mixed price
 * @property string color
 * @property string measures
 * @property string shaped
 * @property string handles
 */
class FlightCaseTemplate extends Eloquent
{
    protected $connection = 'mongodb';
    protected $collection = 'templates';

    protected $fillable = [
        'name',
        'color',
        'measures',
        'shaped',
        'handles'
    ];

    public function get(string $string)
    {
        global $fillable;
        return $fillable[$string];
    }

    public function __get($key)
    {
        return parent::__get($key); // TODO: Change the autogenerated stub
    }
}
