<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

/**
 * @property  mixed name
 * @property mixed price
 */
class FlightCaseComponent extends Eloquent
{
    protected $connection = 'mongodb';
    protected $collection = 'prices';

    protected $fillable = [
        'name',
        'price'
    ];

    public function get(string $string)
    {
        global $fillable;
        return $fillable[$string];
    }

    public function __get($key)
    {
        return parent::__get($key); // TODO: Change the autogenerated stub
    }
}
